#!/usr/bin/env node

const PushBullet = require('pushbullet');
const pusher = new PushBullet(process.env.PUSHBULLET_KEY);
const houses = require('./public/houses.json');

(async function(){
  const { devices } = await pusher.devices();
  houses.map(item => { 
    let {
      href,
      description,
      location,
      price,
      surface,
      date
    } = item;
    date = new Date(date);
    if ((new Date() - date) < 24 *60 * 60 * 1000) {
      devices.map(dev => {
        pusher.link(dev.iden, `${location} ${price} ${surface}`, `http://www.xe.gr${href}`, `${description}`);
      });
    }
  })
})();
